[2024-05-09T11:30:04.557+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T11:30:04.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T11:29:33.127496+00:00 [queued]>
[2024-05-09T11:30:04.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T11:29:33.127496+00:00 [queued]>
[2024-05-09T11:30:04.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-09T11:30:04.837+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-09 11:29:33.127496+00:00
[2024-05-09T11:30:04.854+0000] {standard_task_runner.py:63} INFO - Started process 114651 to run task
[2024-05-09T11:30:04.875+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-09T11:29:33.127496+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpt2be21dl']
[2024-05-09T11:30:04.879+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask transform_load_weather_data
[2024-05-09T11:30:05.023+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T11:29:33.127496+00:00 [running]> on host ubuntu2204
[2024-05-09T11:30:05.308+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T11:29:33.127496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T11:29:33.127496+00:00'
[2024-05-09T11:30:05.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T11:30:07.040+0000] {credentials.py:621} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2024-05-09T11:30:10.474+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T11:30:10.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T11:30:10.487+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-09T11:29:33.127496+00:00, execution_date=20240509T112933, start_date=20240509T113004, end_date=20240509T113010
[2024-05-09T11:30:10.627+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T11:30:10.684+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T11:30:10.698+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
