[2024-05-23T10:05:49.106+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T10:05:49.143+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.load_weather_data manual__2024-05-23T10:04:19.618668+00:00 [queued]>
[2024-05-23T10:05:49.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.load_weather_data manual__2024-05-23T10:04:19.618668+00:00 [queued]>
[2024-05-23T10:05:49.159+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-23T10:05:49.213+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_a.load_weather_data> on 2024-05-23 10:04:19.618668+00:00
[2024-05-23T10:05:49.221+0000] {standard_task_runner.py:63} INFO - Started process 64324 to run task
[2024-05-23T10:05:49.226+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'group_a.load_weather_data', 'manual__2024-05-23T10:04:19.618668+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmpma5rixu8']
[2024-05-23T10:05:49.240+0000] {standard_task_runner.py:91} INFO - Job 172: Subtask group_a.load_weather_data
[2024-05-23T10:05:49.495+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.group_a.load_weather_data manual__2024-05-23T10:04:19.618668+00:00 [running]> on host ubuntu2204
[2024-05-23T10:05:49.808+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='group_a.load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T10:04:19.618668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T10:04:19.618668+00:00'
[2024-05-23T10:05:49.824+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T10:05:49.872+0000] {postgres.py:176} INFO - Running copy expert: COPY weather_data FROM stdin WITH DELIMITER AS ',', filename: current_weather_data_kyiv.csv
[2024-05-23T10:05:49.913+0000] {base.py:84} INFO - Using connection ID '***_conn' for task execution.
[2024-05-23T10:05:50.497+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-23T10:05:50.504+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T10:05:50.566+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag_parallel, task_id=group_a.load_weather_data, run_id=manual__2024-05-23T10:04:19.618668+00:00, execution_date=20240523T100419, start_date=20240523T100549, end_date=20240523T100550
[2024-05-23T10:05:50.757+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-23T10:05:50.799+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T10:05:50.823+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
