[2024-05-23T11:08:35.151+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T11:08:35.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [queued]>
[2024-05-23T11:08:35.267+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [queued]>
[2024-05-23T11:08:35.268+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 5
[2024-05-23T11:08:35.398+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_joined_data> on 2024-05-23 11:02:24.641410+00:00
[2024-05-23T11:08:35.418+0000] {standard_task_runner.py:63} INFO - Started process 86224 to run task
[2024-05-23T11:08:35.442+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'load_joined_data', 'manual__2024-05-23T11:02:24.641410+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmprz5884fx']
[2024-05-23T11:08:35.447+0000] {standard_task_runner.py:91} INFO - Job 198: Subtask load_joined_data
[2024-05-23T11:08:35.612+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [running]> on host ubuntu2204
[2024-05-23T11:08:35.869+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='load_joined_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T11:02:24.641410+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T11:02:24.641410+00:00'
[2024-05-23T11:08:35.887+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T11:08:40.081+0000] {credentials.py:621} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2024-05-23T11:08:55.007+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-23T11:08:55.011+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T11:08:55.056+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag_parallel, task_id=load_joined_data, run_id=manual__2024-05-23T11:02:24.641410+00:00, execution_date=20240523T110224, start_date=20240523T110835, end_date=20240523T110855
[2024-05-23T11:08:55.222+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-23T11:08:55.254+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T11:08:55.281+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
