[2024-05-09T11:31:19.291+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T11:31:19.321+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T11:30:47.429239+00:00 [queued]>
[2024-05-09T11:31:19.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T11:30:47.429239+00:00 [queued]>
[2024-05-09T11:31:19.340+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-09T11:31:19.451+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-09 11:30:47.429239+00:00
[2024-05-09T11:31:19.476+0000] {standard_task_runner.py:63} INFO - Started process 115401 to run task
[2024-05-09T11:31:19.490+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-09T11:30:47.429239+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp03dlx1mk']
[2024-05-09T11:31:19.493+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask transform_load_weather_data
[2024-05-09T11:31:19.696+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T11:30:47.429239+00:00 [running]> on host ubuntu2204
[2024-05-09T11:31:20.086+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T11:30:47.429239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T11:30:47.429239+00:00'
[2024-05-09T11:31:20.089+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T11:31:20.695+0000] {credentials.py:621} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2024-05-09T11:31:22.129+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T11:31:22.134+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T11:31:22.204+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-09T11:30:47.429239+00:00, execution_date=20240509T113047, start_date=20240509T113119, end_date=20240509T113122
[2024-05-09T11:31:22.419+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T11:31:22.502+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T11:31:22.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
