[2024-05-23T08:22:04.961+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T08:22:05.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.transform_load_weather_data manual__2024-05-23T08:21:03.959960+00:00 [queued]>
[2024-05-23T08:22:05.077+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.transform_load_weather_data manual__2024-05-23T08:21:03.959960+00:00 [queued]>
[2024-05-23T08:22:05.079+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-23T08:22:05.147+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_a.transform_load_weather_data> on 2024-05-23 08:21:03.959960+00:00
[2024-05-23T08:22:05.152+0000] {standard_task_runner.py:63} INFO - Started process 12123 to run task
[2024-05-23T08:22:05.156+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'group_a.transform_load_weather_data', 'manual__2024-05-23T08:21:03.959960+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmpqe1xxs_x']
[2024-05-23T08:22:05.158+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask group_a.transform_load_weather_data
[2024-05-23T08:22:05.278+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.group_a.transform_load_weather_data manual__2024-05-23T08:21:03.959960+00:00 [running]> on host ubuntu2204
[2024-05-23T08:22:05.497+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='group_a.transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T08:21:03.959960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T08:21:03.959960+00:00'
[2024-05-23T08:22:05.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T08:22:05.554+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T08:22:05.556+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow/dags/weatherapi_dag.py", line 24, in transform_load_data
    city = data["name"]
           ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-05-23T08:22:05.566+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_parallel, task_id=group_a.transform_load_weather_data, run_id=manual__2024-05-23T08:21:03.959960+00:00, execution_date=20240523T082103, start_date=20240523T082205, end_date=20240523T082205
[2024-05-23T08:22:05.613+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 101 for task group_a.transform_load_weather_data ('NoneType' object is not subscriptable; 12123)
[2024-05-23T08:22:05.654+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T08:22:05.685+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T08:22:05.686+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
