[2024-05-13T08:38:20.176+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T08:38:20.405+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-13T08:38:20.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-13T08:38:20.467+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-13T08:38:20.891+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-12 00:00:00+00:00
[2024-05-13T08:38:20.984+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'scheduled__2024-05-12T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp43l73c3x']
[2024-05-13T08:38:20.998+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask transform_load_weather_data
[2024-05-13T08:38:20.961+0000] {standard_task_runner.py:63} INFO - Started process 2600 to run task
[2024-05-13T08:38:21.720+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data scheduled__2024-05-12T00:00:00+00:00 [running]> on host ubuntu2204
[2024-05-13T08:38:23.432+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T00:00:00+00:00'
[2024-05-13T08:38:23.438+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T08:38:25.629+0000] {credentials.py:621} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2024-05-13T08:38:26.712+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-13T08:38:26.713+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T08:38:26.731+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=scheduled__2024-05-12T00:00:00+00:00, execution_date=20240512T000000, start_date=20240513T083820, end_date=20240513T083826
[2024-05-13T08:38:26.839+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-13T08:38:26.885+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T08:38:26.898+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
