[2024-05-23T08:14:48.709+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T08:14:48.780+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.transform_load_weather_data manual__2024-05-23T08:11:34.055508+00:00 [queued]>
[2024-05-23T08:14:48.807+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.group_a.transform_load_weather_data manual__2024-05-23T08:11:34.055508+00:00 [queued]>
[2024-05-23T08:14:48.807+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-05-23T08:14:48.945+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_a.transform_load_weather_data> on 2024-05-23 08:11:34.055508+00:00
[2024-05-23T08:14:48.972+0000] {standard_task_runner.py:63} INFO - Started process 7355 to run task
[2024-05-23T08:14:48.975+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'group_a.transform_load_weather_data', 'manual__2024-05-23T08:11:34.055508+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmpjwp_u6d1']
[2024-05-23T08:14:48.977+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask group_a.transform_load_weather_data
[2024-05-23T08:14:49.148+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.group_a.transform_load_weather_data manual__2024-05-23T08:11:34.055508+00:00 [running]> on host ubuntu2204
[2024-05-23T08:14:49.495+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='group_a.transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T08:11:34.055508+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T08:11:34.055508+00:00'
[2024-05-23T08:14:49.498+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T08:14:49.539+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T08:14:49.545+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow/dags/weatherapi_dag.py", line 24, in transform_load_data
    city = data["name"]
           ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-05-23T08:14:49.552+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_parallel, task_id=group_a.transform_load_weather_data, run_id=manual__2024-05-23T08:11:34.055508+00:00, execution_date=20240523T081134, start_date=20240523T081448, end_date=20240523T081449
[2024-05-23T08:14:49.621+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 86 for task group_a.transform_load_weather_data ('NoneType' object is not subscriptable; 7355)
[2024-05-23T08:14:49.655+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T08:14:49.712+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T08:14:49.714+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
